CREATE TABLE "certificates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"certificate_identifier" varchar(512) NOT NULL,
	"team_id" uuid NOT NULL,
	"common_name" varchar(255) NOT NULL,
	"serial_number" varchar(128) NOT NULL,
	"certificate_status" varchar(64) NOT NULL,
	"certificate_purpose" varchar(128) NOT NULL,
	"valid_from" timestamp NOT NULL,
	"valid_to" timestamp NOT NULL,
	"subject_alternate_names" text,
	"issuer_ca" varchar(255),
	"environment" varchar(64),
	"is_amex_cert" boolean DEFAULT false NOT NULL,
	"current_cert" boolean,
	"zero_touch" boolean,
	"hosting_team" varchar(255),
	"idaas_id" varchar(128),
	"application_id" varchar(128),
	"request_id" varchar(128),
	"requested_by" varchar(255),
	"requested_for" varchar(255),
	"approved_by" varchar(255),
	"request_channel" varchar(255),
	"cert_type" varchar(64),
	"acknowledged_by" varchar(64),
	"central_id" varchar(64),
	"application_name" varchar(255),
	"comment" text,
	"renewing_team" varchar(255),
	"change_number" varchar(64),
	"server_name" varchar(255),
	"keystore_path" varchar(512),
	"uri" varchar(512),
	"revoke_request_id" varchar(128),
	"revoke_date" timestamp,
	"cert_notifications" jsonb,
	"devices" varchar(255)[],
	"agent_vault_certs" jsonb,
	"ta_client" varchar(64),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"renewed_by" varchar(255),
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "teams" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"team_name" varchar(255) NOT NULL,
	"escalation" varchar(255),
	"alert1" varchar(255),
	"alert2" varchar(255),
	"alert3" varchar(255),
	"snow_group" varchar(255),
	"prc_group" varchar(255),
	"applications" varchar(255)[],
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"updated_by" varchar(255),
	"deleted_at" timestamp,
	CONSTRAINT "teams_team_name_unique" UNIQUE("team_name")
);
--> statement-breakpoint
DROP TABLE "users" CASCADE;--> statement-breakpoint
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "team_cert_unique" ON "certificates" USING btree ("team_id","certificate_identifier");